### ISSUE TITLE
Project review: 05/25/22

### ISSUE THREAD

**Issue by virag-ky** [ha-manel/Tasty#37]
## Code
* the code is very nicely arranged in all of the files
* the module files are straightforward, and the code is well understandable after a first read which is great
* the tests are really simple and they show clearly the AAA method

## UI
* nice color choice for a recipe website
* responsive 

## Readme
* very descriptive
* maybe I would like to see a screenshot of the project

### Great work, I really couldn't find anything which is great, keep up this good work! :+1:

**Comment by ha-manel** [comment]
Hi @virag-ky ! thank you so much for taking the time to check out the project and leave a thorough review ❤️ 
As always your opinions are valued and I will include screenshots of the project in the readme file 😊 thank you again!
